ALTER TABLE words ADD CONSTRAINT unq_words_lemma UNIQUE KEY (lemma);
ALTER TABLE casedwords ADD CONSTRAINT unq_casedwords_cased UNIQUE KEY (cased);
ALTER TABLE senses ADD CONSTRAINT unq_senses_senseid UNIQUE KEY (senseid);
ALTER TABLE senses ADD CONSTRAINT unq_senses_sensekey UNIQUE KEY (sensekey);
ALTER TABLE morphs ADD CONSTRAINT unq_morphs_morph UNIQUE KEY (morph);
ALTER TABLE casedwords ADD INDEX k_casedwords_wordid (wordid);
ALTER TABLE synsets ADD INDEX k_synsets_lexdomainid (lexdomainid);
ALTER TABLE samples ADD INDEX k_samples_synsetid (synsetid);
ALTER TABLE senses ADD INDEX k_senses_synsetid (synsetid);
ALTER TABLE senses ADD INDEX k_senses_wordid (wordid);
ALTER TABLE semlinks ADD INDEX k_semlinks_linkid (linkid);
ALTER TABLE semlinks ADD INDEX k_semlinks_synset1id (synset1id);
ALTER TABLE semlinks ADD INDEX k_semlinks_synset2id (synset2id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_linkid (linkid);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset1id (synset1id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset1id_word1id (synset1id,word1id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset2id (synset2id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset2id_word2id (synset2id,word2id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_word1id (word1id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_word2id (word2id);
ALTER TABLE morphmaps ADD INDEX k_morphmaps_morphid (morphid);
ALTER TABLE morphmaps ADD INDEX k_morphmaps_wordid (wordid);
ALTER TABLE vframemaps ADD INDEX k_vframemaps_frameid (frameid);
ALTER TABLE vframemaps ADD INDEX k_vframemaps_synsetid (synsetid);
ALTER TABLE vframemaps ADD INDEX k_vframemaps_wordid (wordid);
ALTER TABLE vframesentencemaps ADD INDEX k_vframesentencemaps_sentenceid (sentenceid);
ALTER TABLE vframesentencemaps ADD INDEX k_vframesentencemaps_synsetid (synsetid);
ALTER TABLE vframesentencemaps ADD INDEX k_vframesentencemaps_wordid (wordid);
ALTER TABLE adjpositions ADD INDEX k_adjpositions_synsetid (synsetid);
ALTER TABLE adjpositions ADD INDEX k_adjpositions_wordid (wordid);
ALTER TABLE casedwords ADD CONSTRAINT fk_casedwords_wordid FOREIGN KEY k_casedwords_wordid (wordid) REFERENCES words(wordid);
ALTER TABLE synsets ADD CONSTRAINT fk_synsets_lexdomainid FOREIGN KEY k_synsets_lexdomainid (lexdomainid) REFERENCES lexdomains (lexdomainid);
ALTER TABLE samples ADD CONSTRAINT fk_samples_synsetid FOREIGN KEY k_samples_synsetid (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE senses ADD CONSTRAINT fk_senses_synsetid FOREIGN KEY k_senses_synsetid (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE senses ADD CONSTRAINT fk_senses_wordid FOREIGN KEY k_senses_wordid (wordid) REFERENCES words(wordid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_linkid FOREIGN KEY k_semlinks_linkid (linkid) REFERENCES linktypes (linkid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_synset1id FOREIGN KEY k_semlinks_synset1id (synset1id) REFERENCES synsets (synsetid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_synset2id FOREIGN KEY k_semlinks_synset2id (synset2id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_linkid FOREIGN KEY k_lexlinks_linkid (linkid) REFERENCES linktypes (linkid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_synset1id FOREIGN KEY k_lexlinks_synset1id (synset1id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_synset2id FOREIGN KEY k_lexlinks_synset2id (synset2id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_word1id FOREIGN KEY k_lexlinks_word1id (word1id) REFERENCES words (wordid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_word2id FOREIGN KEY k_lexlinks_word2id (word2id) REFERENCES words (wordid);
ALTER TABLE morphmaps ADD CONSTRAINT fk_morphmaps_morphid FOREIGN KEY k_morphmaps_morphid (morphid) REFERENCES morphs(morphid);
ALTER TABLE morphmaps ADD CONSTRAINT fk_morphmaps_wordid FOREIGN KEY k_morphmaps_wordid (wordid) REFERENCES words(wordid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_frameid FOREIGN KEY k_vframemaps_frameid (frameid) REFERENCES vframes(frameid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_synsetid FOREIGN KEY k_vframemaps_synsetid (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_wordid FOREIGN KEY k_vframemaps_wordid (wordid) REFERENCES words(wordid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_sentenceid FOREIGN KEY k_vframesentencemaps_sentenceid (sentenceid) REFERENCES vframesentences(sentenceid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_synsetid FOREIGN KEY k_vframesentencemaps_synsetid (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_wordid FOREIGN KEY k_vframesentencemaps_wordid (wordid) REFERENCES words(wordid);
ALTER TABLE adjpositions ADD CONSTRAINT fk_adjpositions_synsetid FOREIGN KEY k_adjpositions_synsetid (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE adjpositions ADD CONSTRAINT fk_adjpositions_wordid FOREIGN KEY k_adjpositions_wordid (wordid) REFERENCES words (wordid);
